### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by hz97** [hz97/sds192-mp2#1]
Baseline

- [x] for an .Rmd that compiles without errors
- [x] for including the code that wrangled the data
- [x] for using at least two of the five basic verbs (i.e., select(), mutate(), etc.)
- [x]  for annotating your data wrangling pipeline (this can be in a few sentences in text surrounding the R code chunks, or some informative comments inside the R code chunks)
- [x] unnecessary messages from R are hidden from being displayed in the HTML

Average

- [x] for explaining in a single coherent sentence what we can learn from these data
- [x] for using at least one join (e.g. left_join(), inner_join(), etc.)
- [x]  blog post text provides context or background useful in interpreting the graphic
- [x]  for using GitHub for version control

Advanced

- [x] for writing a function to generalize your analysis rather than re-writing the same code multiple times
- [x] for using the Issues tab on GitHub to plan your project
- [ ]  WOW factor: awarded at the professors’ discretion for submissions that are exceptionally compelling
